name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  types:
    runs-on: ubuntu-latest
    name: types
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check types
        run: pnpm test:types
  unit:
    runs-on: ubuntu-latest
    name: unit
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
      - name: Collect coverage
        uses: codecov/codecov-action@v3
        if: success()
        with:
          files: ./coverage/lcov.info
